language: generic
services:
  - docker

before_install:
  - docker build -t suwigyarathore/ci-cd-react -f Dockerfile.dev .

script:
  - docker run -e CI=true suwigyarathore/ci-cd-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "ci-cd-react"
  env: "Cicdreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-153157716099"
  bucket_path: "ci-cd-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY