language: generic
services:
  - docker

before_install:
  - docker build -t suwigyarathore/ci-cd-react -f Dockerfile.dev .

script:
  - docker run -e CI=true suwigyarathore/ci-cd-react npm run test -- --coverage